// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBzewR7Ac1MatYyD8xvx5KCPcfOze-ddA',
    appId: '1:20546983337:web:1b899f5a8ba752d1c8e0b8',
    messagingSenderId: '20546983337',
    projectId: 'worth-rm-soldier-school',
    authDomain: 'worth-rm-soldier-school.firebaseapp.com',
    storageBucket: 'worth-rm-soldier-school.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwqwSRFjRNVBEZniJMUw25Ny4QOiJMyGE',
    appId: '1:20546983337:android:5075dc850b4e78abc8e0b8',
    messagingSenderId: '20546983337',
    projectId: 'worth-rm-soldier-school',
    storageBucket: 'worth-rm-soldier-school.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0R5LNcknj8JI82T9ksrXJMr0TwioC_I',
    appId: '1:20546983337:ios:0dc7d61b94a76e02c8e0b8',
    messagingSenderId: '20546983337',
    projectId: 'worth-rm-soldier-school',
    storageBucket: 'worth-rm-soldier-school.firebasestorage.app',
    iosBundleId: 'com.worthrm.school.worthSoldierSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0R5LNcknj8JI82T9ksrXJMr0TwioC_I',
    appId: '1:20546983337:ios:0dc7d61b94a76e02c8e0b8',
    messagingSenderId: '20546983337',
    projectId: 'worth-rm-soldier-school',
    storageBucket: 'worth-rm-soldier-school.firebasestorage.app',
    iosBundleId: 'com.worthrm.school.worthSoldierSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBzewR7Ac1MatYyD8xvx5KCPcfOze-ddA',
    appId: '1:20546983337:web:e95d4fc6a97166d4c8e0b8',
    messagingSenderId: '20546983337',
    projectId: 'worth-rm-soldier-school',
    authDomain: 'worth-rm-soldier-school.firebaseapp.com',
    storageBucket: 'worth-rm-soldier-school.firebasestorage.app',
  );
}
